# Generated by Django 3.2.18 on 2023-04-30 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='s_liked',
            new_name='is_liked',
        ),
    ]
